config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

	root 'home#index', as: 'home'

	get 'dashboard' => 'home#dashboard', as: 'dashboard'
	get 'admin' => 'admin#index', as: 'admin'
	get 'admin/teacher' => 'admin#teacher', as: 'admin_teacher'
	get 'admin/buycoin' => 'admin#buycoin', as: 'admin_buycoin'
  post 'charge_coin' => 'admin#chargeCoin', as: 'admin_charge_coin'
  post 'cancel_buycoin' => 'admin#cancelBuycoin', as: 'admin_cancel_buycoin'
	get 'admin/exchange' => 'admin#exchange', as: 'admin_exchange'
	post 'exchange_coin' => 'admin#exchangeCoin', as: 'admin_exchange_coin'
	post 'cancel_exchange_coin' => 'admin#cancelExchangeCoin', as: 'admin_cancel_exchange_coin'
	get 'admin/transaction' => 'admin#transaction', as: 'admin_transaction'
	get 'admin/feedback' => 'admin#feedback', as: 'admin_feedback'
  get 'admin/set_cash' => 'admin#set_cash'
  post 'admin/set_cash_proc/:id' => 'admin#set_cash_proc', as: 'set_cash'
  get 'admin/curriculum(/:course_id)' => 'admin#curriculum', as: 'admin_curriculum'
  get 'admin/curriculum_destroy(/:course_id)' => 'admin#destroy', as: 'admin_curriculum_destroy'
  get 'admin/curriculum_hide(/:course_id)' => 'admin#hide', as: 'admin_curriculum_hide'
  post 'admin/create_course' => 'admin#create_course'
  post 'admin/update(/:course_id)' => 'admin#update'
  get 'admin/lesson_history' => 'admin#lesson_history'

	get 'apply_for_teacher' => 'teachers#apply', as: 'apply_for_teacher'
	post 'teachers/apply' => 'teachers#submit_teacher_application', as: 'submit_teacher_application'
	get 'certify_teacher/:id' => 'teachers#certify', as: 'teacher_certify'
  get 'edit_teacher_info' => 'teachers#edit_teacher_info', as: 'edit_teacher_info'
  post 'teacher/update_info' => 'teachers#update_teacher_info', as: 'update_teacher_info'

	get 'find_teacher' => 'teachers#index', as: 'find_teacher'
	get 'teachers/filter_teachers', as: 'filter_teacher'

	get 'teacher/:id' => 'teachers#show', as: 'teacher'
	post 'teacher/add_comment/:id' => 'teachers#add_comment', as: 'teacher_comments'
	delete 'teacher/destroy_comment/:id' => 'teachers#destroy_comment', as: 'destroy_teacher_comment'

	get 'purchase' => 'cash#index', as: 'purchase'
  get 'purchase/buycoin' => 'cash#buycoin', as: 'buycoin'
  get 'purchase/sellcoin' => 'cash#sellcoin', as: 'sellcoin'
  get 'purchase/history' => 'cash#coinhistory', as: 'coinhistory'

	post 'submit_purchase' => 'cash#submit_purchase', as: 'submit_purchase'
	get 'permit_purchase/:id' => 'cash#permit_purchase', as: 'permit_purchase'
	post 'submit_exchange' => 'cash#submit_exchange', as: 'submit_exchange'

	post 'feedback' => 'home#feedback', as: 'feedback'

	get 'book_lesson/:id' => 'lesson#select_time', as: 'select_time'
	post 'book_lesson' => 'lesson#book', as: 'book_path'

	# Lesson
	post 'get_lessons' => 'lesson#getLessons', as: 'get_lessons'
	post 'submit_lesson' => 'lesson#submitLesson', as: 'submit_lesson'
  post 'cancel_lesson' => 'lesson#cancelLesson', as: 'cancel_lesson'

	# Course
	get 'get_courses/:lang' => 'course#getCourses', as: 'get_courses'

  # Lecture Room
  get 'lecture_room' => 'lecture_room#index', as: 'lecture_room'
  get 'self_study' => 'lecture_room#self_study', as: 'self_study'
  get 'take_lesson' => 'lecture_room#take_lesson', as: 'take_lesson'
  get 'give_lesson' => 'lecture_room#give_lesson', as: 'give_lesson'
  get 'lecture_room/get_lesson' => 'lecture_room#get_lesson'
  get 'lecture_room/save_memo' => 'lecture_room#save_memo'
  get 'get_selected_course/:id' => 'lecture_room#get_selected_course'
  get 'get_selected_lesson/:id' => 'lecture_room#get_selected_lesson' # '강의 듣기'에서만 사용
  get 'eval_lesson/:id' => 'lecture_room#eval_lesson'

  post 'confirm_lesson' => 'home#confirm_lesson'
  get 'home/lecture_request_complete'
  get 'home/freematching_request_complete'

  get 'home/disable_user' => 'home#disable_user', as: 'disable_user'

  resources :courses
end

app/views/admin/_menu_list.erb
<!--<a href="/admin/teacher" class="list-group-item <%# if controller.action_name == 'teacher' %>active<%# end %>"> 선생님 목록 </a>-->
<a href="/admin/buycoin" class="list-group-item <% if controller.action_name == 'cash' %>active<% end %>"> 수강권 구매 목록 </a>
<a href="/admin/exchange" class="list-group-item <% if controller.action_name == 'cash' %>active<% end %>"> 수강권 환전 목록 </a>
<a href="/admin/transaction" class="list-group-item <% if controller.action_name == 'cash' %>active<% end %>"> 강의료 목록 </a>
<a href="/admin/set_cash" class="list-group-item <% if controller.action_name == 'set_cash' %>active<% end %>"> 수강권 변경 </a>
<a href="/admin/feedback" class="list-group-item <% if controller.action_name == 'feedback' %>active<% end %>"> 이용자 피드백 </a>
<a href="/admin/curriculum" class="list-group-item <% if controller.action_name == 'curriculum' %>active<% end %>"> 커리큘럼 입력 </a>
<a href="/admin/lesson_history" class="list-group-item <% if controller.action_name == 'lesson_history' %>active<% end %>"> 강의 내역 </a>

app/views/admin/buycoin.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>

    <div class="col-md-10">
      <!-- Teacher requests -->
      <div class="col-md-12">
        <h2> Buy Coin List </h2>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th class="col-md-1">Completion & History ID</th>
              <th class="col-md-1">User name</th>
              <th class="col-md-1">How To Pay</th>
              <th class="col-md-1">Account Holder</th>
              <th class="col-md-2">Account Number</th>
              <th class="col-md-1">Amount</th>
              <th class="col-md-1">Start Date</th>
              <th class="col-md-1">End Date</th>
              <th class="col-md-2">Dispose</th>
            </tr>
          </thead>
          <tbody>
            <% @buycoin_histories.each do |h| %>
              <tr>
                <td id="<%= h.id %>_is_complete"><%= h.id %><%= h.is_complete %></td>
                <td><%= h.user.name %></td>
                <td><%= h.how_to_pay %></td>
                <td><%= h.buycoin.account_holder %></td>
                <td><%= h.buycoin.account_number %></td>
                <td><%= h.amount %></td>
                <td><%= h.start_time.to_s.chop.chop.chop.chop.chop.chop %></td>
                <td><%= h.end_time.to_s.chop.chop.chop.chop.chop.chop || "아직 완료되지 않았습니다." %></td>
                <td>
                  <% if !h.is_complete %>
                    <button type="button" class="btn btn-primary" onclick="chargeCoin(<%= h.id %>, this)">승인</button><button type="button" class="btn btn-primary" onclick="cancelBuycoin(<%= h.id %>, this)">취소</button>
                  <% else %>
                    <% case (h.is_complete and !h.end_time.nil?) %>
                    <% when true %>
                      <button type="button" class="btn btn-default disabled">승인됨</button>
                    <% when false %>
                      <button type="button" class="btn btn-default disabled">취소됨</button>
                    <% end %>
                  <% end %>
                </td>
                <td></td>
                  <%# if h.is_permitted %>
                  <%# else %>
                    <%# link_to permit_purchase_path(h.id), {:class => "btn btn-default"} do %>
                      <%# <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> %>
                    <%# end %>
                  <%# end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- Teacher requests -->

    </div>

  </div>
</div>

<script>
  function chargeCoin(h_id, object) {
    $.ajax({
      type: "POST",
      url: '<%= url_for(:admin_charge_coin) %>',
      data: { history_id: h_id },
      success: function(data) {
        if (data == 'OK') {
          document.getElementById(String(h_id) + "_is_complete").innerHTML = 'true';
          disableButton(object, 'approve');
          object.nextSibling.remove();
        }
      },
      error: function(data) {
          console.log(data);
      }
    });
  }

  function cancelBuycoin(h_id, object) {
    $.ajax({
      type: "POST",
      url: '<%= url_for(:admin_cancel_buycoin) %>',
      data: { history_id: h_id },
      success: function(data) {
        if (data == 'OK') {
          document.getElementById(String(h_id) + "_is_complete").innerHTML = 'true';
          disableButton(object, 'cancel');
          object.previousSibling.remove();
        }
      }
    });
  }

  function disableButton(object, str) {
    if (str == 'approve') $(object).text('승인됨');
    else $(object).text('취소됨');
    $(object).addClass('disabled');
    $(object).removeClass('btn-primary');
    $(object).addClass('btn-default');
  }
</script>

app/views/admin/curriculum.erb
<div class="container">
  <div class="row">
    
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>
    
    <div class="col-md-5">
      <div class="panel panel-default">
        <% if !@modifing_course.nil? %>
          <div class="panel-body">
            <legend>커리큘럼 수정</legend>
            <%= form_for @course, url: ('/admin/update/%d' % @modifing_course.id) do |f| %>
              구분: 
              <%= f.select :lang, ['Korean', 'English', 'Chinese'], selected: @modifing_course.lang %>
              <%= f.select :rank, ['초급', '중급', '고급'], selected: @modifing_course.rank %><br>
              제목: <%= f.text_area :subject, cols: "57", rows: "1", value: @modifing_course.subject %><br>
              내용: <%= f.text_area :content, cols: "57", rows: "20", value: @modifing_course.content %>
              <br>
              <%= f.submit '작성' %>
            <% end %>
          </div>
        <% else %>
          <div class="panel-body">
            <legend>커리큘럼 추가</legend>
            <%= form_for @course, url: '/admin/create_course' do |f| %>
              구분: 
              <%= f.select :lang, ['Korean', 'English', 'Chinese'] %>
              <%= f.select :rank, ['초급', '중급', '고급']%><br>
              제목: <%= f.text_area :subject, cols: "57", rows: "1" %><br>
              내용: <%= f.text_area :content, cols: "57", rows: "20" %>
              <br>
              <%= f.submit '작성' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-body admin-panel">
        <legend>커리큘럼 숨김, 수정, 삭제</legend>
          <% @courses_list.each do |c| %>
            <p>
              <a href="/admin/curriculum/<%= c.id %>"><%= c.lang + ' ' + c.rank + ' ' + c.subject %></a>
              <a href="/admin/curriculum_hide/<%= c.id %>">숨김</a>
              <a href="/admin/curriculum_destroy/<%= c.id %>">삭제</a>
            </p>
          <% end%>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/exchange.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>

    <div class="col-md-10">
      <!-- Teacher requests -->
      <div class="col-md-12">
        <h2> Exchange List </h2>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th class="col-md-1">Completion & History ID</th>
              <th class="col-md-1">User name</th>
              <th class="col-md-1">How To Pay</th>
              <th class="col-md-1">Account Holder</th>
              <th class="col-md-2">Account Number</th>
              <th class="col-md-1">Amount</th>
              <th class="col-md-1">Start Date</th>
              <th class="col-md-1">End Date</th>
              <th class="col-md-2">Dispose</th>
            </tr>
          </thead>
          <tbody>
            <% @exchange_histories.each do |h| %>
              <tr>
                <td id="<%= h.id %>_is_complete"><%= h.id %><%= h.is_complete %></td>
                <td><%= h.user.name %></td>
                <td><%= h.how_to_pay %></td>
                <td><%= h.exchange.account_holder %></td>
                <td><%= h.exchange.account_number %></td>
                <td><%= h.amount %></td>
                <td><%= h.start_time.to_s.chop.chop.chop.chop.chop.chop %></td>
                <td><%= h.end_time.to_s.chop.chop.chop.chop.chop.chop || "아직 완료되지 않았습니다." %></td>
                <td>
                  <% if !h.is_complete %>
                    <button type="button" class="btn btn-primary" onclick="exchangeCoin(<%= h.id %>, this)">승인</button><button type="button" class="btn btn-primary" onclick="cancelExchangeCoin(<%= h.id %>, this)">취소</button>
                  <% else %>
                    <% case (h.is_complete and !h.end_time.nil?) %>
                    <% when true %>
                      <button type="button" class="btn btn-default disabled">승인됨</button>
                    <% when false %>
                      <button type="button" class="btn btn-default disabled">취소됨</button>
                    <% end %>
                  <% end %>
                </td>
                <td></td>
                  <%# if h.is_permitted %>
                  <%# else %>
                    <%# link_to permit_purchase_path(h.id), {:class => "btn btn-default"} do %>
                      <%# <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> %>
                    <%# end %>
                  <%# end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- Teacher requests -->

    </div>

  </div>
</div>

<script>
  function exchangeCoin(h_id, object) {
    $.ajax({
      type: "POST",
      url: '<%= url_for(:admin_exchange_coin) %>',
      data: { history_id: h_id },
      success: function(data) {
        if (data == 'OK') {
          document.getElementById(String(h_id) + "_is_complete").innerHTML = 'true';
          disableButton(object, 'approve');
          object.nextSibling.remove();
        }
      },
      error: function(data) {
          console.log(data);
      }
    });
  }

  function cancelExchangeCoin(h_id, object) {
    $.ajax({
      type: "POST",
      url: '<%= url_for(:admin_cancel_exchange_coin) %>',
      data: { history_id: h_id },
      success: function(data) {
        if (data == 'OK') {
          document.getElementById(String(h_id) + "_is_complete").innerHTML = 'true';
          disableButton(object, 'cancel');
          object.previousSibling.remove();
        }
      },
      error: function(data) {
          console.log(data);
      }
    });
  }

  function disableButton(object, str) {
    if (str == 'approve') $(object).text('승인됨');
    else $(object).text('취소됨');
    $(object).addClass('disabled');
    $(object).removeClass('btn-primary');
    $(object).addClass('btn-default');
  }
</script>

app/views/admin/feedback.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>

    <div class="panel panel-default col-md-10">
      <div class="panel-body">

        <div class="dropdown">
          <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          분류
          <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dLabel">
            <li><a href="/admin/feedback"> 전체 </a></li>
            <li><a href="/admin/feedback?cat=website"> 웹 사이트 기능 관련 </a></li>
            <li><a href="/admin/feedback?cat=curriculum"> 커리큘럼 관련 </a></li>
            <li><a href="/admin/feedback?cat=others"> 기타 </a></li>
          </ul>
        </div>

        <table class="table table-hover">
          <thead>
            <tr>
              <th style="width:10%">피드백 번호</th>
              <th style="width:10%">카테고리</th>
              <th style="width:10%">유저 이름</th>
              <th style="width:20%">유저 아이디</th>
              <th style="width:50%">내용</th>
            </tr>
          </thead>
          
          <tbody>
            <% @feedbacks.each do |f| %>
                <tr>
                  <td style="width:10%"><%= f.id %></td>
                  <td style="width:10%"><%= f.cat %></td>
                  <td style="width:10%"><%= User.unscoped{ f.user.name } %></td>
                  <td style="width:20%"><%= User.unscoped{ f.user.email } %></td>
                  <td style="width:50%"><%= f.text %></td>
                </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    
  </div>
</div>

app/views/admin/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/lesson_history.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>

    <div class="panel panel-default col-md-10">
      <!--<div class="panel-body">-->
        <table class="table table-hover">
          <thead>
            <tr>
              <th style="width:6%">번호</th>
              <th style="width:12%">신청 시각</th>
              <th style="width:10%">선생님 이름<br>(이메일)</th>
              <th style="width:10%">학생 이름<br>(이메일)</th>
              <th style="width:12%">강의 시간</th>
              <th style="width:22%">커리큘럼</th>
              <th style="width:7%">선생<br>수락</th>
              <th style="width:7%">선생<br>거절</th>
              <th style="width:7%">강의<br>종료</th>
              <th style="width:7%">지불<br>완료</th>
            </tr>
          </thead>
            
          <tbody>
            <% @lessons.each do |l| %>
            <tr>
              <td style="width:6%"><%= l.id %></th>
              <td style="width:12%"><%= l.created_at.strftime('%c') %></th>
              <td style="width:10%"><%= l.teacher.name %><br>(<%= l.teacher.email %>)</th>
              <td style="width:10%"><%= l.student.name %><br>(<%= l.student.email %>)</th>
              <td style="width:12%"><%= l.get_period.html_safe %></th>
              <td style="width:22%"><%= l.course.lang %><br><%= l.course.rank %><br><%= l.course.subject %></th>
              <td style="width:7%"><%= l.is_approved %></th>
              <td style="width:7%"><%= l.is_canceled %></th>
              <td style="width:7%"><%= l.teacher_end %></th>
              <td style="width:7%"><%= l.student_end %></th>
            </tr>
            <% end %>
          </tbody>
        <!--
        <div class="col-md-10">
          <th style="width:6%">확정</th>
          <th style="width:6%"><#%= l.confirmed %></th>
          <%# @lessons.each do |l| %>
            선생님: <%#= l.teacher.name %> | <%#= l.teacher.email %><br>
            학생: <%#= l.student.name %> | <%#= l.student.email %><br>
            강의 시간: <%#= l.get_period.html_safe %><br>
            신청한 시간: <%#= l.created_at.strftime('%c') %><br>
            free수업: <%#= l.is_free %><br>
            커리큘럼: <%#= l.course.lang %> | <%#= l.course.rank %> | <%#= l.course.subject %><br>
            confirmed: <%#= l.confirmed %><br>
            is_approved: <%#= l.is_approved %><br>
            is_canceled: <%#= l.is_canceled %><br>
            teacher_end: <%#= l.teacher_end %><br>
            student_end: <%#= l.student_end %><br>
            <hr>
          <%# end %>
        </div>
        -->
        </table>
      <!--</div>-->
    </div>
    
  </div>
</div>

app/views/admin/set_cash.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>
    
    <div class="panel panel-default col-md-10">
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th style="width:15%">유저 번호</th>
              <th style="width:15%">유저 이름</th>
              <th style="width:30%">유저 이메일</th>
              <th style="width:15%">유저 수강권 잔액</th>
              <th style="width:25%">유저 수강권 변경</th>
            </tr>
          </thead>
          
          <tbody>
            <% @users.each do |u| %>
              <%= form_tag(set_cash_path(u.id), method: 'post') do %>
                <tr>
                  <td style="width:15%"><%= u.id %></td>
                  <td style="width:15%"><%= u.name %></td>
                  <td style="width:30%"><%= u.email %></td>
                  <td style="width:15%"><%= u.cash %> 수강권</td>
                  <td style="width:25%">
                    <input class="col-md-8" name="amount" type="number">
                    <input class="col-md-4" type="submit" value="변경">
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
      
  </div>
</div>

app/views/admin/teacher.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>

    <div class="col-md-10">
      <!-- Teacher requests -->
      <div class="col-md-12">
        <h2> Teacher Request </h2>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th class="col-md-9">Name</th>
              <th class="col-md-3">Approve</th>
            </tr>
          </thead>
          <tbody>
            <% @teacher_request.each do |request| %>
              <tr>
                <td><%= request.user.name %></td>
                <td>
                  <%= link_to teacher_certify_path(request.id), {:class => "btn btn-default"} do %>
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- Teacher requests -->

      <!-- Teachers -->
      <div class="col-md-12">
        <h2> Teachers </h2>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th class="col-md-9">Name</th>
            </tr>
          </thead>
          <tbody>
            <% @teachers.each do |teacher| %>
              <tr>
                <td><%= teacher.name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- Teachers -->
    </div>

  </div>
</div>

app/views/admin/transaction.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="list-group">
        <%= render partial: '/admin/menu_list' %>
      </div>
    </div>

    <div class="col-md-10">
      <!-- Teacher requests -->
      <div class="col-md-12">
        <h2> Transaction List </h2>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th class="col-md-2">Completion</th>
              <th class="col-md-2">Receiver</th>
              <th class="col-md-2">Sender</th>
              <th class="col-md-2">Amount</th>
              <th class="col-md-2">Withdrawal Date</th>
              <th class="col-md-2">Deposit Date</th>
            </tr>
          </thead>
          <tbody>
            <% @transaction_histories.each do |h| %>
              <tr>
                <td><%= h.is_complete %></td>
                <td><%= h.receiver_id %></td>
                <td><%= h.sender_id %></td>
                <td><%= h.amount %></td>
                <td><%= h.start_time %></td>
                <td><%= h.end_time %></td>
                  <%# if h.is_permitted %>
                  <%# else %>
                    <%# link_to permit_purchase_path(h.id), {:class => "btn btn-default"} do %>
                      <%# <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> %>
                    <%# end %>
                  <%# end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- Teacher requests -->

    </div>

  </div>
</div>