config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

	root 'home#index', as: 'home'

	get 'dashboard' => 'home#dashboard', as: 'dashboard'
	get 'admin' => 'admin#index', as: 'admin'
	get 'admin/teacher' => 'admin#teacher', as: 'admin_teacher'
	get 'admin/buycoin' => 'admin#buycoin', as: 'admin_buycoin'
  post 'charge_coin' => 'admin#chargeCoin', as: 'admin_charge_coin'
  post 'cancel_buycoin' => 'admin#cancelBuycoin', as: 'admin_cancel_buycoin'
	get 'admin/exchange' => 'admin#exchange', as: 'admin_exchange'
	post 'exchange_coin' => 'admin#exchangeCoin', as: 'admin_exchange_coin'
	post 'cancel_exchange_coin' => 'admin#cancelExchangeCoin', as: 'admin_cancel_exchange_coin'
	get 'admin/transaction' => 'admin#transaction', as: 'admin_transaction'
	get 'admin/feedback' => 'admin#feedback', as: 'admin_feedback'
  get 'admin/set_cash' => 'admin#set_cash'
  post 'admin/set_cash_proc/:id' => 'admin#set_cash_proc', as: 'set_cash'
  get 'admin/curriculum(/:course_id)' => 'admin#curriculum', as: 'admin_curriculum'
  get 'admin/curriculum_destroy(/:course_id)' => 'admin#destroy', as: 'admin_curriculum_destroy'
  get 'admin/curriculum_hide(/:course_id)' => 'admin#hide', as: 'admin_curriculum_hide'
  post 'admin/create_course' => 'admin#create_course'
  post 'admin/update(/:course_id)' => 'admin#update'
  get 'admin/lesson_history' => 'admin#lesson_history'

	get 'apply_for_teacher' => 'teachers#apply', as: 'apply_for_teacher'
	post 'teachers/apply' => 'teachers#submit_teacher_application', as: 'submit_teacher_application'
	get 'certify_teacher/:id' => 'teachers#certify', as: 'teacher_certify'
  get 'edit_teacher_info' => 'teachers#edit_teacher_info', as: 'edit_teacher_info'
  post 'teacher/update_info' => 'teachers#update_teacher_info', as: 'update_teacher_info'

	get 'find_teacher' => 'teachers#index', as: 'find_teacher'
	get 'teachers/filter_teachers', as: 'filter_teacher'

	get 'teacher/:id' => 'teachers#show', as: 'teacher'
	post 'teacher/add_comment/:id' => 'teachers#add_comment', as: 'teacher_comments'
	delete 'teacher/destroy_comment/:id' => 'teachers#destroy_comment', as: 'destroy_teacher_comment'

	get 'purchase' => 'cash#index', as: 'purchase'
  get 'purchase/buycoin' => 'cash#buycoin', as: 'buycoin'
  get 'purchase/sellcoin' => 'cash#sellcoin', as: 'sellcoin'
  get 'purchase/history' => 'cash#coinhistory', as: 'coinhistory'

	post 'submit_purchase' => 'cash#submit_purchase', as: 'submit_purchase'
	get 'permit_purchase/:id' => 'cash#permit_purchase', as: 'permit_purchase'
	post 'submit_exchange' => 'cash#submit_exchange', as: 'submit_exchange'

	post 'feedback' => 'home#feedback', as: 'feedback'

	get 'book_lesson/:id' => 'lesson#select_time', as: 'select_time'
	post 'book_lesson' => 'lesson#book', as: 'book_path'

	# Lesson
	post 'get_lessons' => 'lesson#getLessons', as: 'get_lessons'
	post 'submit_lesson' => 'lesson#submitLesson', as: 'submit_lesson'
  post 'cancel_lesson' => 'lesson#cancelLesson', as: 'cancel_lesson'

	# Course
	get 'get_courses/:lang' => 'course#getCourses', as: 'get_courses'

  # Lecture Room
  get 'lecture_room' => 'lecture_room#index', as: 'lecture_room'
  get 'self_study' => 'lecture_room#self_study', as: 'self_study'
  get 'take_lesson' => 'lecture_room#take_lesson', as: 'take_lesson'
  get 'give_lesson' => 'lecture_room#give_lesson', as: 'give_lesson'
  get 'lecture_room/get_lesson' => 'lecture_room#get_lesson'
  get 'lecture_room/save_memo' => 'lecture_room#save_memo'
  get 'get_selected_course/:id' => 'lecture_room#get_selected_course'
  get 'get_selected_lesson/:id' => 'lecture_room#get_selected_lesson' # '강의 듣기'에서만 사용
  get 'eval_lesson/:id' => 'lecture_room#eval_lesson'

  post 'confirm_lesson' => 'home#confirm_lesson'
  get 'home/lecture_request_complete'
  get 'home/freematching_request_complete'

  get 'home/disable_user' => 'home#disable_user', as: 'disable_user'

  resources :courses
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, :except => [:index]

	def index
	end

	def dashboard
    @lesson_applying = Lesson.where(student: current_user)
    @lesson_applied = Lesson.where(teacher: current_user)
		@lesson_applying = @lesson_applying.paginate(page: params[:page], per_page: 5)
		@lesson_applied = @lesson_applied.paginate(page: params[:page], per_page: 5)
	end

	def feedback
		f = Feedback.new
		f.user = current_user
		f.text = params[:feedback][:text]
		f.cat = params[:cat]
		f.save

		redirect_to :back
	end

  def confirm_lesson
    lesson = Lesson.find(params[:lesson_id].to_i)
    if params[:confirm] == "true"
      lesson.update(confirmed: true)
    else
      lesson.update(is_rejected: true)
    end

    respond_to do |format|
      format.json { render json: {} }
    end
  end

  def lecture_request_complete
  end
  
  def freematching_request_complete
  end
  
  def disable_user
    current_user.update(inactive: true)
    redirect_to '/'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<div class="container" id="dashboard_container">
  <div class="row">

    <!-- Left column -->
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <div  class="col-md-12 text-center">
            <% if current_user.profile_pic.url.nil? %>
              <img src="http://thesocialmediamonthly.com/wp-content/uploads/2015/08/photo.png" class="profile-pic" height="180" width="180"/>
            <% else %>
              <img src=<%= current_user.profile_pic.url %> class="profile-pic" height="180" width="180"/>
            <% end %>
          </div>
          <div class="col-md-12 text-center">
            <h3><%= current_user.name %></h3>
          </div>
          <div class="col-md-12 text-center">
            <a href="/purchase" class="btn btn-sm btn-primary">
              <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
              <%= current_user.cash %><%= t "coin" %>
            </a>
          </div>
        </div>
        <ul class="list-group">
          <li class="list-group-item">
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            <%= t "my_page.profile.personal" %>
          <% end %>
          </li>
          <li class="list-group-item">
          <%= link_to edit_teacher_info_path do %>
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              <%= t "my_page.profile.teaching" %>
            <% end %>
          </li>
        </ul>
      </div>
      
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-md-12">
            <h5>
              <%= t "my_page.feedback.describe" %>
            </h5>
            <div class="form-group">
              <%= form_for :feedback, url: feedback_path do |f| %>
                <div>
                  <select class="form-control" name="cat">
                    <option value="" disabled selected hidden><%= t "my_page.feedback.select" %></option>
                    <option value="website"><%= t "my_page.feedback.website" %></option>
                    <option value="curriculum"><%= t "my_page.feedback.curriculum" %></option>
                    <option value="others"><%= t "my_page.feedback.others" %></option>
                  </select>
                </div>
                <%= f.text_area :text, :autocomplete => :off, rows: "5", class: "col-md-12 form-control" %>
                <%= f.submit (t "my_page.feedback.finish"), class: "btn btn-sm btn-primary col-md-12" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Left column -->

    <!-- Right column -->
    <div class="col-md-9">

      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="lectureinfo-panel-heading">
              <h3> <%= t "my_page.timetable.title" %> </h3>
            </div>
            <div class="panel-body">
              <div class="go-demo-box"></div>
              <!-- Event Calendar by DayPilot -->
              <div id="dp"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="row" >
        <div class="col-md-6" style="padding-right:2px;">
          <div class="panel panel-default">
            <div class="lectureinfo-panel-heading">
              <h3><%= t "my_page.lesson.requiring" %></h3>
            </div>
            <div class="panel-body lectureinfo-panel">
              <% @lesson_applying.reverse_each do |item| %>
                <div class="row" id="lesson_applying<%= item.id %>">
                  <div class=lectureinfo>  
                  
                  <h5>
                  <%= t "my_page.lesson.requiring_message" %> : <%= item.teacher.name %>
                  <% if item.confirmed %>
                    <button type="button" class="btn btn-sm btn-primary disabled"><%= t "my_page.timetable.confirmed" %></button>
                  <% end %>
                  
                  <% if !item.is_canceled %>
                      <% if item.end_at >= DateTime.now %>
                        <button type="button" class="btn btn-sm btn-default" onclick="cancelLesson(<%= item.id %>, this)"><%= t "my_page.lesson.cancel" %></button>
                      <% end %>
                  <% else %>
                    <button type="button" class="btn btn-sm btn-default disabled" onclick="cancelLesson(<%= item.id %>, this)"><%= t "my_page.lesson.canceled" %></button>
                  <% end %>
                  </h5>
                  
                    <h5><%= t "my_page.lesson.time" %> : <%= item.get_period.html_safe %><h5>
                    <h5><%= t "my_page.lesson.curriculum" %> : <%= item.course.lang %> <%= item.course.rank %> <%= item.course.subject %><h5>
                    <!--<h5><%#= t "my_page.lesson.fee" %> : <#%= item.get_price.html_safe %> <#%= t "coin" %></h5>-->
                    <h5><%= t "my_page.lesson.skype_id" %> : <%= item.teacher.skype_id %></h5>
                  </div> 
                </div>
              <% end %>
              <div class="col-md-12" style="text-align: center">
                <%= will_paginate @lesson_applying, previous_label: "« ", next_label: " »" %>
              </div>
            </div>
          </div>
        </div>
        
        <div class="col-md-6" style="padding-left:2px;">
          <div class="panel panel-default">
            <div class="lectureinfo-panel-heading">
              <h3><%= t "my_page.lesson.required" %></h3>
            </div>
            <div class="panel-body lectureinfo-panel">
              <% @lesson_applied.reverse_each do |item| %>
                <div class="row" id="lesson_applied<%= item.id %>">
                  <div class=lectureinfo>
                    <h5><%= t "my_page.lesson.required_message" %> : <%= item.student.name %><span data-lesson_id="<%= item.id.to_s %>" id="confirm_span<%= item.id.to_s %>"><%= item.get_confirm_teacher.html_safe %></span></h5>
                    <h5><%= t "my_page.lesson.time" %> : <%= item.get_period.html_safe %><h5>
                    <h5><%= t "my_page.lesson.curriculum" %> : <%= item.course.lang %> <%= item.course.rank %> <%= item.course.subject %><h5>
                    <!--<h5><%#= t "my_page.lesson.fee" %> : <%#= item.get_price.html_safe %><%#= t "coin" %></h5>-->
                    <h5><%= t "my_page.lesson.skype_id" %> : <%= item.student.teacher_info.skype_id %></h5>
                  </div>    
                </div>
              <% end %>
              <div class="row">
                <div style="text-align: center">
                  <%= will_paginate @lesson_applied, previous_label: "« ", next_label: " »" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        
    <!-- Right column -->

  </div>
</div>

<script src="/assets/daypilot-all.min.js" type="text/javascript"></script>
<script src="/assets/mySchedule.js" type="text/javascript"></script>
<script type="text/javascript">
  var my_avail = new Teacher_Schedule('<%= current_user.get_schedule %>');
  var dp = new DayPilot.Calendar("dp");
  show_availables_on_calendar(dp,my_avail);
  dp.viewType = "Week";
  dp.eventMoveHandling = "Disabled";
  dp.cssClassPrefix = "langdy";
  dp.init();

  loadEvents();

  //load available times

  eventStatic = null; // 이벤트 전역 변수
  // 셀렉트 이벤트 바인딩
  dp.onTimeRangeSelected = function (args) {
    name = "name";
    var e = new DayPilot.Event({
      start: args.start,
      end: args.end,
      id: DayPilot.guid(),
      resource: args.resource,
      text: name
    });

    eventStatic = e;
    // dp.events.add(e);

    // $('#selectTimeModal').modal("hide");
  };

  function loadEvents() {
    $.post("/get_lessons",   // in ASP.NET MVC, use "backend/events"
        {
          user_id: <%= current_user.id %>,
          start: "'" + dp.visibleStart().toString().replace("T", " [").concat("]'"),
          end: "'" + dp.visibleEnd().toString().replace("T", " [").concat("]'")
        },
    function(data, status, xhr) {
      dp.events.list = data;
      dp.update();
    });
  }

  $(document).ready(function(){
    $('.confirm_btn').click(function(){
      confirm_lesson($(this).data('confirmed'), $(this).parent().data('lesson_id'));
    });
  });
  
  function cancelLesson(lesson_id, object) {
    $.ajax({
      type: "POST",
      url: '<%= url_for(:cancel_lesson) %>',
      data: { lesson_id: lesson_id },
      success: function(data) {
        if (data == 'OK') {
          disableCancelButton(object);
        }
      }
    });
  }
  
  function disableCancelButton(object) {
    $(object).text(<%= t "my_page.lesson.canceled" %>);
    $(object).addClass('disabled');
    $(object).removeClass('btn-primary');
    $(object).addClass('btn-default');
  }
</script>

app/views/home/freematching_request_complete.html.erb
<div class="container">
  <div class="outer">
    <div class="inner">
      <div class="panel panel-default">
          <div class="panel-body">
            <h4>무료 매칭 신청이 성공적으로 완료되었습니다.<br><br>
            상대방의 수락 후 강의가 확정되니 조금만 기다려주세요!<br><br>
            무료 매칭 신청이 거절되거나 취소되는 경우 수강권이 반환됩니다.
            </h4>
          </div>
          <div class="panel-body">
            <div style="padding:100px">
              적당한 이미지
            </div>
            <div>
              <a class="btn btn-primary" href="/dashboard" role="button">마이페이지로 가기</a>
            </div>
          </div>
          <div class="panel-body">
            <h4>
            회화의 달인이 되는 그날까지 힘내세요!<br><br>
            랭디는 여러분에게 도움이 될 수 있도록 힘을 내겠습니다.
            </h4>
          </div>    
      </div>
    </div>
  </div>
</div>

app/views/home/lecture_request_complete.html.erb
<div class="container">
  <div class="outer">
    <div class="inner">
      <div class="panel panel-default">
          <div class="panel-body">
            <h4><%= t "request_complete.lesson_message1" %><br><br>
            <%= t "request_complete.lesson_message2" %><br><br>
            <%= t "request_complete.lesson_message3" %>
            </h4>
          </div>
          <div class="panel-body">
            <div>
              <a class="btn btn-primary" href="/dashboard" role="button"><%= t "request_complete.button_to_mypage" %></a>
            </div>
          </div>
          <div class="panel-body">
            <h4>
            <%= t "request_complete.bottom_message1" %><br><br>
            <%= t "request_complete.bottom_message2" %>
            </h4>
          </div>    
      </div>
    </div>
  </div>
</div>

app/views/home/swp_dashboard.html.erb
<div class="container" id="dashboard_container">
  <div class="row">

    <!-- Left column -->
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if current_user.profile_pic.url.nil? %>
            <img src="http://thesocialmediamonthly.com/wp-content/uploads/2015/08/photo.png" class="profile-pic col-md-offset-2 col-md-8"/>
          <% else %>
            <img src=<%= current_user.profile_pic.url %> class="profile-pic col-md-offset-2 col-md-8"/>
          <% end %>
          <div class="col-md-12" style="text-align:center;">
            <h3><%= current_user.name %></h3>
            <a href="/purchase" class="btn btn-sm btn-primary">
              <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
              <%= current_user.cash %>p
            </a>
          </div>
        </div>
        <ul class="list-group">
          <li class="list-group-item">
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            개인 프로필
          <% end %>
          </li>
        </ul>
      </div>

      <% unless current_user.is_teacher or not current_user.teacher_info.nil? %>
        <ul class="list-group">
          <%= link_to apply_for_teacher_path do %>
            <li class="list-group-item">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            Apply for being a teacher
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if current_user.is_teacher %>
        <ul class="list-group">
          <%= link_to edit_teacher_info_path do %>
            <li class="list-group-item">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            학습 프로필
            </li>
          <% end %>
        </ul>
      <% end %>

      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-md-12">
            <h5>
              언제든지 의견을 남겨주세요. 여러분의 의견에 항상 귀기울이겠습니다.
            </h5>
            <%= form_for :feedback, url: feedback_path do |f| %>
              <%= f.text_field :text, :autocomplete => :off, class: "col-md-12 form-control" %>
              <%= f.submit "피드백 남기기", class: "btn btn-default col-md-12" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- Left column -->

    <!-- Right column -->
    <div class="col-md-9">

      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="lectureinfo-panel-heading">
              <h3> 강의시간표 </h3>
            </div>
            <div class="panel-body">
              <!-- Event Calendar by DayPilot -->
              <div id="dp"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="row" >
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="lectureinfo-panel-heading">
              <h3>내가 신청한 강의</h3>
            </div>
          <div class="panel-body lectureinfo-panel">
            
          <!--
          <div class="row">
            <div class="col-md-1 column first-column">
              <h4>단계</h4>
            </div>
            <div class="col-md-1 column">
              <h4>언어</h4>
            </div>
            <div class="col-md-2 column">
              <h4>챕터</h4>
            </div>
            <div class="col-md-2 column">
              <h4>선생님 성함</h4>
            </div>
            <div class="col-md-2 column">
              <h4>수강 기간</h4>
            </div>
            <div class="col-md-2 column">
              <h4>수강 가격</h4>
            </div>
            <div class="col-md-2 column">
              <h4>수강 확정 여부</h4>
            </div>
          </div>
          -->
          <% @lesson_applying.each do |item| %>
            <div class="row" id="lesson_applying<%= item.id %>">
              <div class=lectureinfo>  
                <h4><%= item.teacher.name %>님에게 강의를 신청하였습니다.</h4>
                <h5>강의 시간 : <%= item.get_period.html_safe %><h5>
                <h5>커리큘럼 : <%= item.course.lang %> <%= item.course.rank %> <%= item.course.subject %><h5>
                <h5>강의료 : <%= item.get_price.html_safe %> 수강권</h5>
              </div> 
            </div>
            <!--
              <div class="col-md-1 column first-column">
                <%#= item.course.rank %>
              </div>
              <div class="col-md-1 column">
                <%#= item.course.lang %>
              </div>
              <div class="col-md-2 column">
                <%#= item.course.subject %>
              </div>
              <div class="col-md-2 column">
                <%#= item.teacher.name %>
              </div>
              <div class="col-md-2 column">
                <%#= item.get_period.html_safe %>
              </div>
              <div class="col-md-2 column">
                시간당 <%#= item.get_price.html_safe %> 수강권
              </div>
              <div class="col-md-2 column">
                <span data-lesson_id="<%#= item.id.to_s %>" id="confirm_span<%#= item.id.to_s %>"><%#= item.get_confirm_student.html_safe %></span>
              </div>
            -->
          <% end %>
          
          </div>
          </div>
        </div>
        </div>
        
        <div class="row" >
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="lectureinfo-panel-heading">
              <h3>나에게 신청된 강의</h3>
            </div>
            <div class="panel-body lectureinfo-panel">
            
            <!--
            <div class="row">
              <div class="col-md-1 column first-column">
                <h4>단계</h4>
              </div>
              <div class="col-md-1 column">
                <h4>언어</h4>
              </div>
              <div class="col-md-2 column">
                <h4>챕터</h4>
              </div>
              <div class="col-md-2 column">
                <h4>학생 성함</h4>
              </div>
              <div class="col-md-2 column">
                <h4>수강 기간</h4>
              </div>
              <div class="col-md-2 column">
                <h4>수강 가격</h4>
              </div>
              <div class="col-md-2 column">
                <h4>수강 확정 여부</h4>
              </div>
            </div>
            -->
            
            <% @lesson_applied.each do |item| %>
              <div class="row" id="lesson_applied<%= item.id %>">
                <div class=lectureinfo>
                  <h4><%= item.student.name %>님이 강의를 신청하였습니다.<span data-lesson_id="<%= item.id.to_s %>" id="confirm_span<%= item.id.to_s %>"><%= item.get_confirm_teacher.html_safe %></span></h4>
                  <h5>강의 시간 : <%= item.get_period.html_safe %><h5>
                  <h5>커리큘럼 : <%= item.course.lang %> <%= item.course.rank %> <%= item.course.subject %><h5>
                  <h5>강의료 : <%= item.get_price.html_safe %> 수강권</h5>
                </div>    
              <!--
                <div class="col-md-1 column first-column">
                  <#%= item.course.rank %>
                </div>
                <div class="col-md-1 column">
                  <#%= item.course.lang %>
                </div>
                <div class="col-md-1 column">
                  <#%= item.course.subject %>
                </div>
                <div class="col-md-2 column">
                  <#%= item.student.name %>
                </div>
                <div class="col-md-2 column">
                  <#%= item.get_period.html_safe %>
                </div>
                <div class="col-md-2 column">
                  시간당 <#%= item.get_price.html_safe %> 수강권
                </div>
                <div class="col-md-2 column">
                  <span data-lesson_id="<#%= item.id.to_s %>" id="confirm_span<#%= item.id.to_s %>"><#%= item.get_confirm_teacher.html_safe %></span>
                </div>
              </div>
              -->
            <% end %>
            </div>
          </div>
        </div>
        </div>
        
    <!-- Right column -->

  </div>
</div>

<script src="/assets/daypilot-all.min.js" type="text/javascript"></script>
<script src="/assets/mySchedule.js" type="text/javascript"></script>
<script type="text/javascript">
  var my_avail = new Teacher_Schedule('<%= current_user.get_schedule %>');
  var dp = new DayPilot.Calendar("dp");
  show_availables_on_calendar(dp,my_avail);
  dp.viewType = "Week";
  dp.eventMoveHandling = "Disabled";
  dp.init();

  loadEvents();

  //load available times

  eventStatic = null; // 이벤트 전역 변수
  // 셀렉트 이벤트 바인딩
  dp.onTimeRangeSelected = function (args) {
    name = "name";
    var e = new DayPilot.Event({
      start: args.start,
      end: args.end,
      id: DayPilot.guid(),
      resource: args.resource,
      text: name
    });

    eventStatic = e;
    // dp.events.add(e);

    // $('#selectTimeModal').modal("hide");
  };

  function loadEvents() {
    $.post("/get_lessons",   // in ASP.NET MVC, use "backend/events"
        {
          user_id: <%= current_user.id %>,
          start: "'" + dp.visibleStart().toString().replace("T", " [").concat("]'"),
          end: "'" + dp.visibleEnd().toString().replace("T", " [").concat("]'")
        },
    function(data, status, xhr) {
      dp.events.list = data;
      dp.update();
    });
  }

  $(document).ready(function(){
    $('.confirm_btn').click(function(){
      confirm_lesson($(this).data('confirmed'), $(this).parent().data('lesson_id'));
    });
  });
</script>