config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

	root 'home#index', as: 'home'

	get 'dashboard' => 'home#dashboard', as: 'dashboard'
	get 'admin' => 'admin#index', as: 'admin'
	get 'admin/teacher' => 'admin#teacher', as: 'admin_teacher'
	get 'admin/buycoin' => 'admin#buycoin', as: 'admin_buycoin'
  post 'charge_coin' => 'admin#chargeCoin', as: 'admin_charge_coin'
  post 'cancel_buycoin' => 'admin#cancelBuycoin', as: 'admin_cancel_buycoin'
	get 'admin/exchange' => 'admin#exchange', as: 'admin_exchange'
	post 'exchange_coin' => 'admin#exchangeCoin', as: 'admin_exchange_coin'
	post 'cancel_exchange_coin' => 'admin#cancelExchangeCoin', as: 'admin_cancel_exchange_coin'
	get 'admin/transaction' => 'admin#transaction', as: 'admin_transaction'
	get 'admin/feedback' => 'admin#feedback', as: 'admin_feedback'
  get 'admin/set_cash' => 'admin#set_cash'
  post 'admin/set_cash_proc/:id' => 'admin#set_cash_proc', as: 'set_cash'
  get 'admin/curriculum(/:course_id)' => 'admin#curriculum', as: 'admin_curriculum'
  get 'admin/curriculum_destroy(/:course_id)' => 'admin#destroy', as: 'admin_curriculum_destroy'
  get 'admin/curriculum_hide(/:course_id)' => 'admin#hide', as: 'admin_curriculum_hide'
  post 'admin/create_course' => 'admin#create_course'
  post 'admin/update(/:course_id)' => 'admin#update'
  get 'admin/lesson_history' => 'admin#lesson_history'

	get 'apply_for_teacher' => 'teachers#apply', as: 'apply_for_teacher'
	post 'teachers/apply' => 'teachers#submit_teacher_application', as: 'submit_teacher_application'
	get 'certify_teacher/:id' => 'teachers#certify', as: 'teacher_certify'
  get 'edit_teacher_info' => 'teachers#edit_teacher_info', as: 'edit_teacher_info'
  post 'teacher/update_info' => 'teachers#update_teacher_info', as: 'update_teacher_info'

	get 'find_teacher' => 'teachers#index', as: 'find_teacher'
	get 'teachers/filter_teachers', as: 'filter_teacher'

	get 'teacher/:id' => 'teachers#show', as: 'teacher'
	post 'teacher/add_comment/:id' => 'teachers#add_comment', as: 'teacher_comments'
	delete 'teacher/destroy_comment/:id' => 'teachers#destroy_comment', as: 'destroy_teacher_comment'

	get 'purchase' => 'cash#index', as: 'purchase'
  get 'purchase/buycoin' => 'cash#buycoin', as: 'buycoin'
  get 'purchase/sellcoin' => 'cash#sellcoin', as: 'sellcoin'
  get 'purchase/history' => 'cash#coinhistory', as: 'coinhistory'

	post 'submit_purchase' => 'cash#submit_purchase', as: 'submit_purchase'
	get 'permit_purchase/:id' => 'cash#permit_purchase', as: 'permit_purchase'
	post 'submit_exchange' => 'cash#submit_exchange', as: 'submit_exchange'

	post 'feedback' => 'home#feedback', as: 'feedback'

	get 'book_lesson/:id' => 'lesson#select_time', as: 'select_time'
	post 'book_lesson' => 'lesson#book', as: 'book_path'

	# Lesson
	post 'get_lessons' => 'lesson#getLessons', as: 'get_lessons'
	post 'submit_lesson' => 'lesson#submitLesson', as: 'submit_lesson'
  post 'cancel_lesson' => 'lesson#cancelLesson', as: 'cancel_lesson'

	# Course
	get 'get_courses/:lang' => 'course#getCourses', as: 'get_courses'

  # Lecture Room
  get 'lecture_room' => 'lecture_room#index', as: 'lecture_room'
  get 'self_study' => 'lecture_room#self_study', as: 'self_study'
  get 'take_lesson' => 'lecture_room#take_lesson', as: 'take_lesson'
  get 'give_lesson' => 'lecture_room#give_lesson', as: 'give_lesson'
  get 'lecture_room/get_lesson' => 'lecture_room#get_lesson'
  get 'lecture_room/save_memo' => 'lecture_room#save_memo'
  get 'get_selected_course/:id' => 'lecture_room#get_selected_course'
  get 'get_selected_lesson/:id' => 'lecture_room#get_selected_lesson' # '강의 듣기'에서만 사용
  get 'eval_lesson/:id' => 'lecture_room#eval_lesson'

  post 'confirm_lesson' => 'home#confirm_lesson'
  get 'home/lecture_request_complete'
  get 'home/freematching_request_complete'

  get 'home/disable_user' => 'home#disable_user', as: 'disable_user'

  resources :courses
end

app/controllers/teachers_controller.rb
require 'will_paginate'
require 'will_paginate/active_record'

class TeachersController < ApplicationController
	before_action :authenticate_user!
	before_action :require_admin_login, only: [:certify]

	def apply
	end

	def submit_teacher_applicatio
		t = TeacherInfo.new(teacher_application_params)
		t.user = current_user
		t.save

		redirect_to :dashboard
	end

	def certify
		t = TeacherInfo.find(params[:id])
		t.is_approved = true
		t.save

		u = t.user
		u.is_teacher = true
		u.save

		redirect_to :back
	end

	def index
		########################
		# 초기 선생님 찾기 시 목록
		# 1. is_teacher가 ture
		# 2. skype_id가 not null
		# 3. Order는 로그인 횟수
		########################
		@teachers = User.joins(:teacher_info).where(is_teacher: true).where("lang_to_teach_1 != ? OR lang_to_teach_2 != ? OR lang_to_teach_3 != ?", "", "", "").where("is_teacher = ? AND users.skype_id is NOT NULL", true).order(sign_in_count: :desc)

		@teachers = @teachers.paginate(page: params[:page], per_page: 5)
	end

	def filter_teachers
		# 시간 설정 되어있을 경우 available_time 테이블 JOIN, 아니면 하지 않음 (teacher_info만 JOIN)
		if !params[:day_of_week].nil? && !params[:day_of_week].empty? || !params[:time].nil? && !params[:time].empty?
			@teachers = User.joins(:available_times).joins(:teacher_info).where("is_teacher = ? AND users.skype_id is NOT NULL", true)
		else
			@teachers = User.joins(:teacher_info).where(is_teacher: true).where("is_teacher = ? AND users.skype_id is NOT NULL", true)
		end

		# 성별
		if !params[:gender].nil? && !params[:gender].empty?
			@teachers = @teachers.where(gender: params[:gender])
		end

		# 언어		
		if !params[:language].nil? && !params[:language].empty?
			@teachers = @teachers.where("lang_to_teach_1 = ? OR lang_to_teach_2 = ? OR lang_to_teach_3 = ?", params[:language], params[:language], params[:language])
		end

		# 강의 요일
		if !params[:day_of_week].nil? && !params[:day_of_week].empty?
			@teachers = @teachers.where(available_times: { week_day: params[:day_of_week] })
		end
		
		# 강의 시간
		if !params[:time].nil? && !params[:time].empty?
			time_specific_start = nil
			time_specific_end = nil
			
			if params[:time] == '0'
				time_specific_start = DateTime.new(2000, 1, 1, 0, 0, 0)
			elsif params[:time] == '1'
				time_specific_start = DateTime.new(2000, 1, 1, 6, 0, 0)
			elsif params[:time] == '2'
				time_specific_start = DateTime.new(2000, 1, 1, 12, 0, 0)
			else
				time_specific_start = DateTime.new(2000, 1, 1, 18, 0, 0)
			end
			
			time_specific_end = time_specific_start.advance(:hours => 6)
			
			@teachers = @teachers.where("available_times.start_at >= ? AND available_times.start_at < ? OR available_times.end_at >= ? AND available_times.end_at < ? OR available_times.start_at <= ? AND available_times.end_at > ?", time_specific_start, time_specific_end, time_specific_start, time_specific_end, time_specific_start, time_specific_end)
		end
		
		# 평점순
		if params[:sort_rating] == 'y'
			@teachers = @teachers.order("rating DESC")
		else # 평점순이 아닌경우는 로그인 횟수순 정렬
			@teachers = @teachers.order("sign_in_count DESC")
		end
		
		@teachers = @teachers.paginate(page: params[:page], per_page: 5)

		render :index
	end

	def show
    @teacher = User.find(params[:id].to_i)
		if !current_user.is_admin and !@teacher.is_teacher
			redirect_to find_teacher_path
		end
	end

	def add_comment
		c = TeacherComment.new
		c.commentee = User.find(params[:id])
		c.commentor = current_user
		c.text = params[:new_comment][:text]
		c.save

		redirect_to :back
	end

	def destroy_comment
		c = TeacherComment.find(params[:id])
		c.destroy

		redirect_to :back
	end

  def edit_teacher_info
    @teacher_info = current_user.teacher_info
  end

  def update_teacher_info
    teacher_info = current_user.teacher_info
    teacher_info.update(teacher_application_params)
    
    # user 테이블에도 skype_id가 있음
    current_user.skype_id = teacher_application_params["skype_id"]
    current_user.save
    
    current_user.set_schedule(params[:schedules])
    redirect_to :dashboard
  end

  private

  def teacher_application_params
    params.require(:teacher_info).permit(:brief_introduction, :location, :major, :skype_id, :school_grad, :introduction, :lecture_price)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_curriculum_modal.erb
<div class="modal fade in" id="curriculumModal" tabindex="-1" role="dialog" aria-labelledby="curriculumLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="curriculumLabel"><%= t "teacher.curriculum.title" %></h4>
      </div>
      <div class="modal-body curriculumModal">
        <ul id="tree-tab" class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#tree-ko">한국어</a></li>
          <li><a data-toggle="tab" href="#tree-ch">中文</a></li>
          <!--<li><a data-toggle="tab" href="#tree-en">English</a></li>-->
        </ul>
        
        <div id="tree-wrapper" class="tab-content">
          <div id="tree-ko" class="tab-pane fade active"></div>
          <div id="tree-ch" class="tab-pane fade"></div>
          <!--<div id="tree-en" class="tab-pane fade"></div>-->
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t "teacher.curriculum.cancel" %></button>
        <button id="curri_btn" type="button" class="btn btn-primary" data-dismiss="modal"><%= t "teacher.curriculum.select" %></button>
      </div>
    </div>
  </div>
</div>

app/views/teachers/apply.html.erb
<br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="col-md-offset-2 col-md-10">
      <h3> Application form </h3>
      <hr>
      </div>
      <%= form_for :teacher_info, url: submit_teacher_application_path do |f| %>

        <div class="col-md-2" align="center">
          <%= f.label :location, "Location", class: "control-label" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :location, :autocomplete => :off, class: "col-md-12 form-control" %>
        </div>
        <div class="col-md-12" style="height: 10px"></div>

        <div class="col-md-2" align="center">
          <%= f.label :major, "Major", class: "control-label" %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :major, :autocomplete => :off, class: "col-md-12 form-control" %>
        </div>
        <div class="col-md-2" align="center">
          <%= f.label :school_grad, "University graduated", class: "control-label" %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :school_grad, :autocomplete => :off, class: "col-md-12 form-control" %>
        </div>
        <div class="col-md-12" style="height: 10px"></div>

        <div class="col-md-2" align="center">
          <%= f.label :introduction, "Introduction", class: "control-label" %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :introduction, :autocomplete => :off, :placeholder => "Explain yourself...", class: "col-md-12 form-control", rows: "15" %>
        </div>
        <div class="col-md-12" style="height: 10px"></div>

        <div class="col-md-12" style="height: 20px"></div>

        <div class="col-md-2"></div>
        <div class="col-md-10">
          <%= f.submit "Submit!", class: "col-md-3 btn btn-primary" %>
        </div>

      <% end %>
    </div>


  </div>
</div>

app/views/teachers/asdf_filter_teachers.html.erb
<% if @teachers.empty? %>
  <h3>
    Sorry. There's no corresponding teacher.
  </h3>
<% else %>
  <% @teachers.each do |t| %>
    <ul class="media-list">
      <div class="panel panel-default">
        <div class="panel-body">
          <li class="media">
            <div class="media-left">
              <%= link_to teacher_path(t) do %>
                <% if t.profile_pic.url.nil? %>
                  <img class="media-object profile-pic" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQV5Y81SdqnTLFEXe_h-4KA2uT4DuNhON4XU32Ut6JkTl2rFDEiOMnmOA" alt="..." height="126" width="126">
                <% else %>
                  <img class="media-object profile-pic" src=<%= t.profile_pic.url %> alt="..." height="126" width="126">
                <% end %>
              <% end %>
            </div>
            <div class="media-body">
              <div class="col-md-9">
                <div class="col-md-3">
                  <%= link_to teacher_path(t) do %>
                    <h3 class="media-heading">
                      <%= t.name %>
                    </h3>
                  <% end %>
                </div>
                <div class="col-md-9" style="height: 30px;"></div>
                <p>
                <span class="label label-success"><%= t.native_lang %></span>
                /
                <span class="label label-default"><%= t.teacher_info.rating %> rating</span>
                /
                <span class="label label-primary"><%= t.teacher_info.lecture_number %> Lessons finished </span>
                </p>
                <p>
                <%= t.teacher_info.brief_introduction %>
                </p>
              </div>

              <div class="col-md-3">
                <h4 style="margin-top: 50px;">
                  <%= t.teacher_info.lecture_price %> coins / 1 hour
                </h4>
                <%# <a href="#" class="btn btn-success btn-sm col-md-12">Book trial lesson</a> %>
              </div >
            </div>
          </li>
        </div>
      </div>
    </ul>

  <% end %>
<% end %>

app/views/teachers/filter_teachers.html.erb
<% if @teachers.empty? %>
  <h3>
    Sorry. There's no corresponding teacher.
  </h3>
<% else %>
  <% @teachers.each do |t| %>
    <ul class="media-list">
      <div class="panel panel-default">
        <div class="panel-body">
          <li class="media">
            <div class="media-left">
              <%= link_to teacher_path(t) do %>
                <% if t.profile_pic.url.nil? %>
                  <img class="media-object profile-pic" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQV5Y81SdqnTLFEXe_h-4KA2uT4DuNhON4XU32Ut6JkTl2rFDEiOMnmOA" alt="..." height="126" width="126">
                <% else %>
                  <img class="media-object profile-pic" src=<%= t.profile_pic.url %> alt="..." height="126" width="126">
                <% end %>
              <% end %>
            </div>
            <div class="media-body">
              <div class="col-md-9">
                <div class="col-md-3">
                  <%= link_to teacher_path(t) do %>
                    <h3 class="media-heading">
                      <%= t.name %>
                    </h3>
                  <% end %>
                </div>
                <div class="col-md-9" style="height: 30px;"></div>
                <p>
                <span class="label label-success"><%= t.native_lang %></span>
                /
                <span class="label label-default"><%= t.teacher_info.rating %> rating</span>
                /
                <span class="label label-primary"><%= t.teacher_info.lecture_number %> Lessons finished </span>
                </p>
                <p>
                <%= t.teacher_info.brief_introduction %>
                </p>
              </div>

              <div class="col-md-3">
                <h4 style="margin-top: 50px;">
                  <%= t.teacher_info.lecture_price %> coins / 1 hour
                </h4>
                <%# <a href="#" class="btn btn-success btn-sm col-md-12">Book trial lesson</a> %>
              </div >
            </div>
          </li>
        </div>
      </div>
    </ul>

  <% end %>
<% end %>

app/views/teachers/index.html.erb
<div class="container">
  <div class="row">
    <!-- Left column -->
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= form_tag("/teachers/filter_teachers", method: "GET") do %>
            <input type="hidden" name="locale" value=<%= I18n.locale %>>
            <div class="col-md-3" id="small-padding">
              <%#= label_tag('label', "배우고 싶은 언어") %>
              <!-- 라벨 태그 삭제해도 되는지?-->
              <%= select_tag :language, options_for_select([[(t "teacher.filter.language_to_learn"), ''], ['English', 'English'], ['한국어', 'Korean'], ['中文', 'Chinese']], params[:language]), { :class => 'form-control' } %>
            </div>
            <div class="col-md-2" id="small-padding">
              <%#= label_tag('label', "강의 요일") %>
              <%= select_tag :day_of_week, options_for_select([[(t "teacher.filter.lesson_day"), ''], [(t "teacher.filter.lesson_day_mon"), 'Monday'], [(t "teacher.filter.lesson_day_tue"), 'Tuesday'], [(t "teacher.filter.lesson_day_wed"), 'Wednesday'], [(t "teacher.filter.lesson_day_thu"), 'Thursday'], [(t "teacher.filter.lesson_day_fri"), 'Friday'], [(t "teacher.filter.lesson_day_sat"), 'Saturday'], [(t "teacher.filter.lesson_day_sun"), 'Sunday']], params[:day_of_week]), { :class => 'form-control' } %>
            </div>
            <div class="col-md-2" id="small-padding"> 
              <%#= label_tag('label', "강의 시간") %>
              <%= select_tag :time, options_for_select([[(t "teacher.filter.lesson_time"), ''], ['00:00 ~ 05:59', 0], ['06:00 ~ 11:59', 1], ['12:00 ~ 17:59', 2], ['18:00 ~ 23:59', 3]], params[:time]), { :class => 'form-control' } %>
            </div>
            <div class="col-md-3" id="small-padding">
              <%#= label_tag('label', "선생님 성별") %>
              <%= select_tag :gender, options_for_select([[(t "teacher.filter.teacher_gender"), ''], [(t "teacher.filter.teacher_gender_male"), 'Male'], [(t "teacher.filter.teacher_gender_female"), 'Female']], params[:gender]), { :class => 'form-control' } %>
            </div>
            <div class="col-md-2" id="small-padding">
              <%= submit_tag (t "teacher.filter.browse"), { :class => 'form-control btn btn-primary', :id => 'submit' } %>
            </div>
            <div class="col-md-5" id="small-padding">
              <% if params[:sort_rating] == 'y' %>
                <%= check_box_tag 'sort_rating', 'y', true %><%= t "teacher.filter.according_to_rate" %>
              <% else %>
                <%= check_box_tag 'sort_rating', 'y', false %><%= t "teacher.filter.according_to_rate" %>
              <% end %>
            </div>
        </div>
        <% end %>
      </div>

      <div class="panel panel-default">
        <div class="panel-body" id="user_list">
          <% if @teachers.to_a == [] %>
            <h4 style="color: #e15242;"><%= t "teacher.filter.no_result" %></h4> 
          <% else %>
            <% @teachers.each do |t| %>
              <ul class="media-list">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <li class="media">
                      <div class="media-left">
                        <%= link_to teacher_path(t) do %>
                          <% if t.profile_pic.url.nil? %>
                            <img class="media-object profile-pic" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQV5Y81SdqnTLFEXe_h-4KA2uT4DuNhON4XU32Ut6JkTl2rFDEiOMnmOA" alt="..." height="126" width="126">
                          <% else %>
                            <img class="media-object profile-pic" src=<%= t.profile_pic.url %> alt="..." height="126" width="126">
                          <% end %>
                        <% end %>
                      </div>
                      <div class="media-body">
                        <div class="col-md-9">
                          <div class="col-md-12">
                            <%= link_to teacher_path(t) do %>
                              <h3 class="media-heading">
                                <%= t.name %>
                              </h3>
                            <% end %>
                          </div>
                          <div class="col-md-12">
                            <h5><b><%= t "teacher.info.language_to_teach" %></b>
                              <% if !t.lang_to_teach_1.nil? and t.lang_to_teach_1 != '' %>
                                <%= t.lang_to_teach_1 %>(<%= t.rank_to_teach_1 %>)
                              <% end %>
                              <% if !t.lang_to_teach_2.nil? and t.lang_to_teach_2 != '' %>
                                <%= t.lang_to_teach_2 %>(<%= t.rank_to_teach_2 %>)
                              <% end %>
                              <% if !t.lang_to_teach_3.nil? and t.lang_to_teach_3 != '' %>
                                <%= t.lang_to_teach_3 %>(<%= t.rank_to_teach_3 %>)
                              <% end %>
                            </h5>
                          </div>
                          <div class="col-md-12">
                            <h5><b><%= t "teacher.info.language_to_learn" %></b>
                              <% if !t.lang_to_learn_1.nil? and t.lang_to_learn_1 != '' %>
                                <%= t.lang_to_learn_1 %>(<%= t.rank_to_learn_1 %>)
                              <% end %>
                              <% if !t.lang_to_learn_2.nil? and t.lang_to_learn_2 != '' %>
                                <%= t.lang_to_learn_2 %>(<%= t.rank_to_learn_2 %>)
                              <% end %>
                              <% if !t.lang_to_learn_3.nil? and t.lang_to_learn_3 != '' %>
                                <%= t.lang_to_learn_3 %>(<%= t.rank_to_learn_3 %>)
                              <% end %>
                            </h5>
                          </div>
                            <!--
                            <div class="col-md-12">
                              <h5><b>가능한 언어 </b>
                                <%# lang_array = [t.lang_to_teach_1, t.lang_to_teach_2, t.lang_to_teach_3, t.lang_to_learn_1, t.lang_to_learn_2, t.lang_to_learn_3] %>
                                <%# rank_array = [t.rank_to_teach_1, t.rank_to_teach_2, t.rank_to_teach_3, t.rank_to_learn_1, t.rank_to_learn_2, t.rank_to_learn_3] %>
                                <%# lang_array = lang_array.compact %>
                                <%# rank_array = rank_array.compact %>
                                <%# res_str = "" %>
                                <%# lang_array.each_with_index do |l, i| %>
                                  <%# res_str += l + '(' + rank_array[i] + ')' + ' ' %>
                                <%# end %>
                                <%#= res_str %>
                              </h5>
                            </div>
                            
                            <%# if !t.lang_to_teach_1.nil? %>
                            <div>
                              <h5><b><%#= t.lang_to_teach_1 %>(<%#= t.rank_to_teach_1 %>)</b></h5>
                              <span class="label label-success"><%#= t.lang_to_teach_1 %></span>
                            </div>
                            <%# end %>
                            <%# if !t.lang_to_teach_2.nil? %>
                            <div>
                              <h5><b><%#= t.lang_to_teach_2 %>(<%#= t.rank_to_teach_2 %>)</b></h5>
                              <span class="label label-success"><%#= t.lang_to_teach_2 %></span>
                            </div>
                            <%# end %>
                            -->
                          <div class="col-md-12">
                            <p>
                              <%= t.teacher_info.brief_introduction %>
                            </p>
                          </div>
                        </div>
                        <div class="col-md-3">
                           <div class="col-md-12">
                            <h5 class="text-center"><%= t "teacher.info.the_number_of_lessons" %></h5>
                            <h4 class="text-center"><b><%= t.teacher_info.lecture_number or 0 %><%= t "teacher.info.times" %></b></h4>
                            <!--<span class="label label-primary"><%#= t.teacher_info.lecture_number %> Lessons finished </span>-->
                          </div>
                          <div class="col-md-12">
                            <h5 class="text-center"><%= t "teacher.info.rating" %></h5>
                            <h4 class="text-center"><b><%= t.teacher_info.rating or 0 %><%= t "teacher.info.score" %></b></h4>
                            <!--<span class="label label-default "><%#= t.teacher_info.rating %>rating</span>-->
                          </div>
                          <!--
                          <div class="col-md-12">
                            <h5 class="text-center"><%#= t "teacher.info.fee" %></h5>
                            <h4 class="text-center"><b><%#= t.teacher_info.lecture_price or 0 %><%#= t "coin" %></b></h4>
                          </div>
                          -->
                          <%# link_to "Book trial lesson", select_time_path(t), class: "btn btn-success btn-sm col-md-12" %>
                        </div>
                      </div>
                    </li>
                  </div>
                </div>
              </ul>
            <% end %>
          <% end %>

          <div class="row">
            <div style="text-align: center">
              <%= will_paginate @teachers, previous_label: "« 이전", next_label: "다음 »" %>
            </div>
          </div>

        </div>
      </div>
    </div>
    <!-- Left column -->

    <!-- Right column -->
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><%= t "teacher.tip" %></div>
        <div class="panel-body">
          <ul>
            <li>Welcome</li>
            <li>Welcome</li>
          </ul>
        </div>
      </div>
      <% unless current_user.is_teacher or not current_user.teacher_info.nil? %>
        <ul class="list-group">
          <%= link_to apply_for_teacher_path do %>
            <li class="list-group-item">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              Apply for being a teacher
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <!-- Right column -->
  </div>
</div>